name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17.0.7'
        distribution: 'temurin'
        cache: gradle

    - run: echo $DEBUG_KEY | base64 -d > debug.keystore
    - name: setting google-service.json
      env:
        DATA: ${{ $GOOGLE_SERVICE }}
      run: echo $DATA /home/runner/work/NGOL-Android/NGOL-Android/app/google-services.json
    - run: echo "NAVER_BASE_URL=\"NAVER_BASE_URL\"" >> local.properties
    - run: echo "NAVER_CLIENT_ID=\"NAVER_CLIENT_ID\"" >> local.properties
    - run: echo "NAVER_CLIENT_SECRET=\"NAVER_CLIENT_SECRET\"" >> local.properties
    - run: echo "GOOGLE_CLIENT_ID=\"GOOGLE_CLIENT_ID\"" >> local.properties
    - run: echo "KAKAO_NATIVE_APP_KEY=\"KAKAO_NATIVE_APP_KEY\"" >> local.properties
    - run: echo "KAKAO_SCHME=\"KAKAO_SCHME\"" >> local.properties
    - run: echo "BASE_URL=\"BASE_URL\"" >> local.properties
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug
