name: Android CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17.0.7'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - run: echo $DEBUG_KEY | base64 -d > debug.keystore
    - name: Create file
      run: cat /home/runner/work/NGOL-Android/NGOL-Android/app/google-services.json | base64
    - name: Putting data
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA > /home/runner/work/NGOL-Android/NGOL-Android/app/google-services.json
    - name: Setting Local Properties
      env:
        NAVER_BASE_URL: ${{ secrets.NAVER_BASE_URL }}
        NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
        NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        KAKAO_NATIVE_APP_KEY: ${{ secrets.KAKAO_NATIVE_APP_KEY }}
        KAKAO_SCHME: ${{ secrets.KAKAO_SCHME }}
        BASE_URL: ${{ secrets.BASE_URL }}
      run: |
        echo "NAVER_BASE_URL=\"$NAVER_BASE_URL\"" >> local.properties
        echo "NAVER_CLIENT_ID=\"$NAVER_CLIENT_ID\"" >> local.properties
        echo "NAVER_CLIENT_SECRET=\"$NAVER_CLIENT_SECRET\"" >> local.properties
        echo "GOOGLE_CLIENT_ID=\"$GOOGLE_CLIENT_ID\"" >> local.properties
        echo "KAKAO_NATIVE_APP_KEY=\"$KAKAO_NATIVE_APP_KEY\"" >> local.properties
        echo "KAKAO_SCHME=\"$KAKAO_SCHME\"" >> local.properties
        echo "BASE_URL=\"$BASE_URL\"" >> local.properties
    - name: Build with Gradle
      run: ./gradlew assembleDebug